# -*- coding: utf-8 -*-
"""BDMDPAI_SAlSADEESPARRAGO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lNC1oXtDHJ-BnDWZrhVo08-kzg9jbXS
"""

# ============================================================
# BALANCE DE MASA - SALSA DE ESPÁRRAGO (VERSIÓN COMPACTA)
# ============================================================

import ipywidgets as widgets
import matplotlib.pyplot as plt
from IPython.display import display
import numpy as np

def calcular(F, Mcorte, Mselec, Mpulpeo, CMC, GMS, NaCl, AC):
    # Cálculos según diagrama de flujo
    despues_corte = F - Mcorte
    despues_seleccion = despues_corte - Mselec
    pulpa = despues_seleccion - Mpulpeo

    # Verificar que no haya masas negativas
    if pulpa < 0:
        print("\n⚠️ ERROR: Las mermas exceden la masa disponible en alguna etapa!")
        print(f"   Pulpa obtenida: {pulpa:.3f} kg (negativo)")
        print(f"   Revise los valores de las mermas:")
        print(f"   • Corte: {Mcorte:.3f} kg")
        print(f"   • Selección: {Mselec:.3f} kg")
        print(f"   • Pulpeado: {Mpulpeo:.3f} kg")
        print(f"   • Total mermas: {Mcorte+Mselec+Mpulpeo:.3f} kg")
        print(f"   • Espárrago fresco: {F:.3f} kg")
        return

    # Aditivos (porcentajes del diagrama)
    total_aditivos_pct = (CMC + GMS + NaCl + AC) / 100
    aditivos_kg = pulpa * total_aditivos_pct

    # Producto final (antes de esterilización)
    PF = pulpa + aditivos_kg

    # Resultados
    print(f"\n{'='*50}")
    print(f"🥫 PRODUCTO FINAL (SALSA): {PF:.3f} kg ({PF*1000:.0f} g)")
    print(f"📊 Rendimiento: {(PF/F)*100:.1f}%")
    print(f"📉 Mermas totales: {Mcorte+Mselec+Mpulpeo:.3f} kg")
    print(f"\n📋 DETALLE DEL PROCESO:")
    print(f"   • Después de corte: {despues_corte:.3f} kg")
    print(f"   • Después de selección: {despues_seleccion:.3f} kg")
    print(f"   • Pulpa obtenida: {pulpa:.3f} kg")
    print(f"   • Aditivos agregados: {aditivos_kg:.3f} kg")
    print(f"\n📝 DESGLOSE DE ADITIVOS:")
    print(f"   • CMC: {pulpa * CMC/100:.4f} kg ({CMC}%)")
    print(f"   • GMS: {pulpa * GMS/100:.4f} kg ({GMS}%)")
    print(f"   • NaCl: {pulpa * NaCl/100:.4f} kg ({NaCl}%)")
    print(f"   • Ác. cítrico: {pulpa * AC/100:.4f} kg ({AC}%)")
    print(f"{'='*50}\n")

    # Gráfico 1: Evolución del proceso
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    etapas = ['Espárrago\nfresco', 'Después\ncorte', 'Después\nselección', 'Pulpa\nobtenida', 'Salsa\nfinal']
    valores = [F, despues_corte, despues_seleccion, pulpa, PF]
    colors = ['#4CAF50', '#8BC34A', '#FFC107', '#FF9800', '#F44336']

    bars = ax1.bar(etapas, valores, color=colors, edgecolor='black')
    for bar, v in zip(bars, valores):
        ax1.text(bar.get_x()+bar.get_width()/2, v+max(valores)*0.02,
                f'{v:.3f}kg', ha='center', fontweight='bold', fontsize=9)
    ax1.set_ylabel('Masa (kg)')
    ax1.set_title('Evolución durante el proceso')
    ax1.grid(axis='y', alpha=0.3)
    ax1.tick_params(axis='x', rotation=15)

    # Gráfico 2: Distribución
    distribucion = {'Salsa final': PF, 'Mermas': Mcorte+Mselec+Mpulpeo, 'Aditivos': aditivos_kg}
    ax2.pie(distribucion.values(), labels=distribucion.keys(), autopct='%1.1f%%',
            colors=['#4CAF50', '#F44336', '#2196F3'], explode=(0.1,0,0))
    ax2.set_title(f'Distribución (Base: {F} kg espárrago)')

    plt.tight_layout()
    plt.show()

# INTERFAZ - SOLO ESPÁRRAGO
print("🥫 BALANCE DE MASA - SALSA DE ESPÁRRAGO")
print("="*50)
print("Ajusta los parámetros y haz clic en CALCULAR")
print("="*50)

# Crear contenedores organizados
print("\n📦 MATERIA PRIMA:")
F = widgets.FloatSlider(
    min=0, max=5, step=0.1, value=2.5,
    description='Espárrago fresco (kg):',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='500px')
)

print("\n🔪 MERMAS (kg):")
Mcorte = widgets.FloatSlider(min=0, max=2, step=0.05, value=0.3,
                            description='Corte (kg):',
                            style={'description_width': 'initial'},
                            layout=widgets.Layout(width='400px'))
Mselec = widgets.FloatSlider(min=0, max=1, step=0.05, value=0.2,
                            description='Selección (kg):',
                            style={'description_width': 'initial'},
                            layout=widgets.Layout(width='400px'))
Mpulpeo = widgets.FloatSlider(min=0, max=2, step=0.05, value=0.4,
                             description='Pulpeado (kg):',
                             style={'description_width': 'initial'},
                             layout=widgets.Layout(width='400px'))

print("\n🧪 ADITIVOS (% del peso de la pulpa):")
CMC = widgets.FloatSlider(min=0, max=1, step=0.05, value=0.2,
                         description='CMC (%):',
                         style={'description_width': 'initial'})
GMS = widgets.FloatSlider(min=0, max=2, step=0.05, value=0.8,
                         description='GMS (%):',
                         style={'description_width': 'initial'})
NaCl = widgets.FloatSlider(min=0, max=5, step=0.1, value=1.5,
                          description='NaCl (%):',
                          style={'description_width': 'initial'})
AC = widgets.FloatSlider(min=0, max=1, step=0.05, value=0.1,
                        description='Ác. cítrico (%):',
                        style={'description_width': 'initial'})

# Etiquetas informativas
info_text = widgets.HTML(value="""
<div style='background-color: #e8f5e9; padding: 10px; border-radius: 5px; margin: 10px 0; border-left: 4px solid #4CAF50;'>
<b>ℹ️ INFORMACIÓN:</b><br>
• El espárrago fresco puede variar de 0 a 5 kg<br>
• Las mermas están en kilogramos (kg)<br>
• Los aditivos se calculan como porcentaje del peso de la pulpa obtenida<br>
• Verificar que las mermas no excedan la masa disponible en cada etapa<br>
• El rendimiento típico esperado es de 30-45%
</div>
""")

# Mostrar valores actuales
def actualizar_valores(change):
    pass  # Los sliders ya muestran sus valores

btn = widgets.Button(description='🔍 CALCULAR SALSA', button_style='primary',
                    layout=widgets.Layout(width='200px', margin='10px 0'))
out = widgets.Output(layout=widgets.Layout(border='1px solid #ccc', padding='10px',
                                           margin='10px 0'))

def on_click(b):
    with out:
        out.clear_output()
        calcular(F.value, Mcorte.value, Mselec.value, Mpulpeo.value,
                CMC.value, GMS.value, NaCl.value, AC.value)

btn.on_click(on_click)

# Organizar la interfaz
ui = widgets.VBox([
    F,
    widgets.HBox([Mcorte, Mselec, Mpulpeo], layout=widgets.Layout(justify_content='space-between')),
    widgets.HBox([CMC, GMS, NaCl, AC], layout=widgets.Layout(justify_content='space-between')),
    info_text,
    widgets.HBox([btn], layout=widgets.Layout(justify_content='center')),
    out
])

display(ui)